name: HW2 - autopep8 Format
permissions:
  contents: write
on:
  push:
    paths:
      - 'HW2/**'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade autopep8
    - name: Generate trace with autopep8
      run: |
        date >> ./HW2/post_traces/autopep8_trace.txt 2>&1 && autopep8 --in-place --aggressive --aggressive --verbose --recursive ./HW2  >> ./HW2/post_traces/autopep8_trace.txt 2>&1 && echo "" >> ./HW2/post_traces/autopep8_trace.txt 2>&1
    - name: Commit and Push changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name 'katydu'
        git config --local user.email 'katydu@users.noreply.github.com'
        git add .
        git commit -m "Update autopep8_trace.txt" || echo "No changes to commit"
        git push