name: Pyflakes Static Analysis
permissions:
  contents: write
on:
  push:
    paths:
      - 'HW2/**'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13.0-rc.1"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyflakes
    - name: Generate trace with pyflakes
      run: |
        (pyflakes HW2/src/* && echo "No errors found by pyflake") &> HW2/post_traces/pyflakes.txt  
    - name: Commit and Push changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name 'SiddhiKhairee'
        git config --local user.email 'SiddhiKhairee@users.noreply.github.com'
        git add .
        git commit -m "Update pyflakes.txt" || echo "No changes to commit"
        git push